### ISSUE TITLE
Add shortcut to cancel screenshot

### ISSUE THREAD

**Issue by s1hofmann** [20hoibe/stack#20]
Currently there's no way to cancel a screenshot. This is quite annoying when accidentally using the wrong shortcut.

**Comment by DaAitch** [comment]
Fixed with #11

**Comment by s1hofmann** [comment]
Can't confirm this. Quickly closing windows is enabled for the `CreateTask` window, but currently there's no possibility to cancel a screenshot.

**Comment by DaAitch** [comment]
when I use branch `feature/preact-parcel-setup` from #11 and make a screenshot with the shortcut, I can close it with that shortcut again. There is a new `toggle...` implementation.
https://github.com/20hoibe/stack/blob/f90be7917c5e26e741a419ab18cdde6a9375b4b8/src/electron.js#L194

I tested on Ubuntu and Mac.

**Comment by s1hofmann** [comment]
Ah, now I get your point!

What I referred to is the possibility to dismiss the screenshot window by pressing `Escape`, like it's also possible with the `CreateTask` window. I think it's not the best UX if it's possible for one window but not the other.

**Comment by DaAitch** [comment]
Understand. So we can add this, too, correct. I've also added, that `createTask` window can be closed with Ctrl/Cmd+Shift+J. Don't know where it is right now :smile: at least in one of the open PRs.
