### ISSUE TITLE
Missmatch between accelerator and shortcut

### ISSUE THREAD

**Issue by s1hofmann** [20hoibe/stack#27]
`Show current task` shows `Shift + Cmd|Ctrl + N` in tray, which does not correspond to the registered shortcut.
```js
globalShortcut.register('CmdOrCtrl+Shift+I', notifyCurrentTask);
```

**Comment by s1hofmann** [comment]
I'd suggest to stick with `CmdOrCtrl+Shift+I`, since `CmdOrCtrl+Shift+N` is a far more common shortcut.

**Comment by DaAitch** [comment]
Yeah, let's use  `+I`
