### ISSUE TITLE
Make `stack` a `Singleton`

### ISSUE THREAD

**Issue by s1hofmann** [20hoibe/stack#29]
Currently it's possible to run multiple instances of stack in parallel, causing global shortcuts to execute `N` times.

![bildschirmfoto 2018-10-05 um 23 26 55](https://user-images.githubusercontent.com/7813765/46561238-1c2d2c80-c8f7-11e8-842b-03de28d2f457.png)

![bildschirmfoto 2018-10-05 um 23 27 12](https://user-images.githubusercontent.com/7813765/46561235-18010f00-c8f7-11e8-906f-115f7b5abad7.png)

To avoid this behaviour, we should make stack a [single instance](https://github.com/electron/electron/blob/v0.36.10/docs/api/app.md#appmakesingleinstancecallback)

**Comment by DaAitch** [comment]
@s1hofmann I think we should fix this also with Milestone 1
